### ISSUE TITLE
IPv4+IPv6 network parsing error in wireguard

### ISSUE THREAD

**Issue by telmich** [O-X-L/ansible-opnsense#3]
When trying to add a wireguard server with 2 IPs, 1 IPv6 address and one 1 IPv4, I get the following error:

```
"Allowed-ip entry '2a0a:e5c0::1/64' is neither a valid IP-address nor a valid network!"
```

Adding this address manually to opnsense however works, and it's fine according to sipcalc.

```
% sipcalc 2a0a:e5c0::1/64
-[ipv6 : 2a0a:e5c0::1/64] - 0

[IPV6 INFO]
Expanded Address	- 2a0a:e5c0:0000:0000:0000:0000:0000:0001
Compressed address	- 2a0a:e5c0::1
Subnet prefix (masked)	- 2a0a:e5c0:0:0:0:0:0:0/64
Address ID (masked)	- 0:0:0:0:0:0:0:1/64
Prefix address		- ffff:ffff:ffff:ffff:0:0:0:0
Prefix length		- 64
Address type		- Aggregatable Global Unicast Addresses
Network range		- 2a0a:e5c0:0000:0000:0000:0000:0000:0000 -
			  2a0a:e5c0:0000:0000:ffff:ffff:ffff:ffff
```

The problem seems to stem from the usage of ip_network:

```
>>> ipaddress.ip_network("2a0a:e5c0::1/64")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.10/ipaddress.py", line 79, in ip_network
    return IPv6Network(address, strict)
  File "/usr/lib/python3.10/ipaddress.py", line 2216, in __init__
    raise ValueError('%s has host bits set' % self)
ValueError: 2a0a:e5c0::1/64 has host bits set
```

Using strict=False fixes this:

```
>>> ipaddress.ip_network("2a0a:e5c0::1/64", strict=False)
IPv6Network('2a0a:e5c0::/64')
```

The same issue happens for IPv4 + IPv6. The correct patch is probably in helper/main.py. I am not sure if there are situations in which we only want to allow a network without host part, but in case of wireguard, for setting the in-tunnel address, the host part is required.

**Comment by ansibleguy** [comment]
Greetings!

I've implemented the ```strict=False``` option.

Thanks for testing.
