### ISSUE TITLE
Problem: Unable to connect to firewall using IPv6

### ISSUE THREAD

**Issue by QlemWasTaken** [O-X-L/ansible-opnsense#82]
### Modules

module_utils/base

### Version

```bash
ansibleguy.opnsense 1.2.9 (latest, downloaded through git)
```

### Ansible Version

```bash
ansible [core 2.17.1]
```

### OPNSense Version

```bash
24.7 (latest)
```

### OPNSense-Plugin Version

```bash
N/A
```

### Issue

When providing an IPv6 address (either using an inventory or directly with the `firewall` variable), ansible is unable to connect to OPNsense. It's error exit (see traceback below).

I think it's due to the way the firewall URL is being created.

At line 33 in `plugins/module_utils/base/api.py` the address of the firewall (whether IPv4, FQDN, or in this case IPv4) is parsed in the `base_url` f-string :
```python
        return httpx.Client(
            base_url=f"https://{self.m.params['firewall']}:{self.m.params['api_port']}/api",
            auth=(self.m.params['api_key'], self.m.params['api_secret']),
            timeout=httpx.Timeout(timeout=timeout, connect=2.0),
            transport=httpx.HTTPTransport(
                verify=ssl_verification(module=self.m),
                retries=self.m.params['api_retries'],
            ),
        )
```

When using an IPv6, it generates an invalid URL, something like :
```
base_url = "https://fd00:75:xx::42:443/api"
```
Which should be as follow instead (see [RFC 3986](https://datatracker.ietf.org/doc/html/rfc3986#section-3.2.2) ):
```
base_url = "https://[fd00:75:xx::42]:443/api"
```
Leading to httpx trying to infer part of the address as (an invalid) port.

I've tried to add the brace around the address in the firewall var :
```yaml
  module_defaults:
    group/ansibleguy.opnsense.all:
        firewall: "[{{ ansible_host }}]"
```
But I get another error, which seem to stem from a validity check of the address :
```
"msg": "Host '[fd00:75:xx::42]' is neither a valid IP nor Domain-Name!"
```

For the record, I've tried to add and reference a FQDN associated with the IPv6 address and it works as intended.

I'm not sure what's the best way to fix this. Maybe add a check for IPv6 before, and generate URL with or without brace accordingly ? I've tried to use urllib.parse but at least on my machine, it also generates invalid URL.

### Config Ansible

```yaml
---
- name: Ansible virtual machines playbook
  hosts: tofu
  connection: local
  gather_facts: false
  module_defaults:
    group/ansibleguy.opnsense.all:
        firewall: "{{ ansible_host }}"
        api_credential_file: '[redacted]'
        ssl_verify: false
  tasks:
    - name: Pulling routes
      ansibleguy.opnsense.list:
        target: 'route'
      register: existing_routes

    - name: Printing
      ansible.builtin.debug:
        var: existing_routes.data
```

### Debug Output

```bash
The full traceback is:
Traceback (most recent call last):
  File "/Users/qlem/Documents/src/repo/ansible/venv/lib/python3.12/site-packages/httpx/_urlparse.py", line 346, in normalize_port
    port_as_int = int(port)
                  ^^^^^^^^^
ValueError: invalid literal for int() with base 10: '75:xx::42:443'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/qlem/.ansible/tmp/ansible-tmp-1721982106.654411-20044-105714620536643/AnsiballZ_list.py", line 107, in <module>
    _ansiballz_main()
  File "/Users/qlem/.ansible/tmp/ansible-tmp-1721982106.654411-20044-105714620536643/AnsiballZ_list.py", line 99, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/Users/qlem/.ansible/tmp/ansible-tmp-1721982106.654411-20044-105714620536643/AnsiballZ_list.py", line 47, in invoke_module
    runpy.run_module(mod_name='ansible_collections.ansibleguy.opnsense.plugins.modules.list', init_globals=dict(_module_fqn='ansible_collections.ansibleguy.opnsense.plugins.modules.list', _modlib_path=modlib_path),
  File "<frozen runpy>", line 226, in run_module
  File "<frozen runpy>", line 98, in _run_module_code
  File "<frozen runpy>", line 88, in _run_code
  File "/var/folders/lg/hqf6812d5fl__8r53vr5hbr00000gn/T/ansible_ansibleguy.opnsense.list_payload__7og2qyj/ansible_ansibleguy.opnsense.list_payload.zip/ansible_collections/ansibleguy/opnsense/plugins/modules/list.py", line 411, in <module>
  File "/var/folders/lg/hqf6812d5fl__8r53vr5hbr00000gn/T/ansible_ansibleguy.opnsense.list_payload__7og2qyj/ansible_ansibleguy.opnsense.list_payload.zip/ansible_collections/ansibleguy/opnsense/plugins/modules/list.py", line 407, in main
  File "/var/folders/lg/hqf6812d5fl__8r53vr5hbr00000gn/T/ansible_ansibleguy.opnsense.list_payload__7og2qyj/ansible_ansibleguy.opnsense.list_payload.zip/ansible_collections/ansibleguy/opnsense/plugins/modules/list.py", line 380, in run_module
  File "/var/folders/lg/hqf6812d5fl__8r53vr5hbr00000gn/T/ansible_ansibleguy.opnsense.list_payload__7og2qyj/ansible_ansibleguy.opnsense.list_payload.zip/ansible_collections/ansibleguy/opnsense/plugins/module_utils/main/route.py", line 40, in __init__
  File "/var/folders/lg/hqf6812d5fl__8r53vr5hbr00000gn/T/ansible_ansibleguy.opnsense.list_payload__7og2qyj/ansible_ansibleguy.opnsense.list_payload.zip/ansible_collections/ansibleguy/opnsense/plugins/module_utils/base/cls.py", line 19, in __init__
  File "/var/folders/lg/hqf6812d5fl__8r53vr5hbr00000gn/T/ansible_ansibleguy.opnsense.list_payload__7og2qyj/ansible_ansibleguy.opnsense.list_payload.zip/ansible_collections/ansibleguy/opnsense/plugins/module_utils/base/api.py", line 21, in __init__
  File "/var/folders/lg/hqf6812d5fl__8r53vr5hbr00000gn/T/ansible_ansibleguy.opnsense.list_payload__7og2qyj/ansible_ansibleguy.opnsense.list_payload.zip/ansible_collections/ansibleguy/opnsense/plugins/module_utils/base/api.py", line 32, in _start
  File "/Users/qlem/Documents/src/repo/ansible/venv/lib/python3.12/site-packages/httpx/_client.py", line 643, in __init__
    super().__init__(
  File "/Users/qlem/Documents/src/repo/ansible/venv/lib/python3.12/site-packages/httpx/_client.py", line 179, in __init__
    self._base_url = self._enforce_trailing_slash(URL(base_url))
                                                  ^^^^^^^^^^^^^
  File "/Users/qlem/Documents/src/repo/ansible/venv/lib/python3.12/site-packages/httpx/_urls.py", line 115, in __init__
    self._uri_reference = urlparse(url, **kwargs)
                          ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/qlem/Documents/src/repo/ansible/venv/lib/python3.12/site-packages/httpx/_urlparse.py", line 248, in urlparse
    parsed_port: int | None = normalize_port(port, scheme)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/qlem/Documents/src/repo/ansible/venv/lib/python3.12/site-packages/httpx/_urlparse.py", line 348, in normalize_port
    raise InvalidURL(f"Invalid port: {port!r}")
httpx.InvalidURL: Invalid port: '75:xx::42:443'
```

**Comment by ansibleguy** [comment]
@QlemWasTaken Thank you for informing me about this issue!

Please install the latest version and re-try it: `ansible-galaxy collection install git+https://github.com/ansibleguy/collection_opnsense.git`

**Comment by QlemWasTaken** [comment]
Just tried and it works as intended. Thanks for the fix !
